Car showroom 04
palakz-simform/VueJS pull request #4
Opened 2023-04-28 14:10 UTC by palakz-simform

This is Practical-4 where I have used axios methods for getting and setting car data from API

2023-05-18 11:00 UTC, Moksha-S requested changes
- Need code formatting  on some file
- check naming convention for emit events

2023-05-18 11:00 UTC, moksha-shah-simform commented on car-showroom-04/src/App.vue
> +            this.showModal = true;
remove unnecessary  coma

2023-05-18 11:00 UTC, moksha-shah-simform commented on car-showroom-04/src/components/car-form.vue
> +        <button class="button" @click="showModalx">x</button>
- Use pointer cursor on button click

2023-05-19 06:21 UTC, Moksha-S approved these changes

2023-05-19 06:21 UTC, merged